In [2]:
print(10**-3)

0.001


In [13]:
import numpy as np
import random as rand

a = np.random.random(10)
print(a)

[0.00829494 0.73003454 0.43609538 0.5329558  0.6000155  0.83698709
 0.88968901 0.73622188 0.21890825 0.37114113]


In [8]:
a.argmax()

8

In [18]:
rand.random()

0.7210848998366157

In [24]:
rand.randint(0, 3)

0

In [26]:
b = np.random.random((2,5))
print(b)
b[0].argmax()

[[0.50086252 0.33348456 0.3193076  0.96900752 0.90838535]
 [0.28939172 0.96715903 0.06776247 0.02220797 0.96079979]]


3

In [30]:
a = np.zeros(1)
print(a.shape)

(1,)


In [34]:
a = np.append(a, 2)

print(a)

[0. 2.]


In [52]:
exp = np.empty((1,4), int)
print(exp.shape)
exp[0] = [1, 3, 3, 5]
exp = np.append(exp, [[5,6,7,8]], axis=0)
print(exp)

(1, 4)
[[1 3 3 5]
 [5 6 7 8]]


In [57]:
a = np.zeros(1, int)

print(a.shape)

(1,)


In [59]:
print(a[-1])

0


In [72]:
a = np.array([1,2,3,4])
b = np.array([5,4,3,2])
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 4, 3, 2]])

In [69]:
a = np.array([1.0, 2.0, 3.0, 4.0]).astype(int)

array([1, 2, 3, 4])

In [63]:
b,x,v,c = a

print(b, x, v, c)

1 2 3 4


In [86]:
a = np.empty((0,4))
print(a)

a = np.append(a, np.array([[1, 1, 1, 1]]), axis=0)

if np.array([1,1,1,1]) not in a:
    print(True)

[]


In [89]:
x = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8]])
y = np.array([1, 10, 12, 8])

# y in x
np.any(np.all(y == x, axis=1))

False

In [116]:
print(np.array([1,8]) not in x[:, :2])

print(x[:,:2])

np.size(np.where(x[:,:2] == np.array([5,6])))
print(np.where(x[:,:2] == np.array([5,6]))[0][0])
# print(x[, :])

False
[[1 2]
 [5 6]]
1


In [121]:
x = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [1, 2, 5, 6],
              [1, 2, 0, 2]])

s = 1
a = 2

print(x[np.all(x[:, :2] == np.array([s,a]), axis = 1)])

[[1 2 3 4]
 [1 2 5 6]
 [1 2 0 2]]
